# Data related arguments
data_name: synthetic/celeux_s2_static
data_source: None
data_path: datasets
data_vars: "--export_targets celeux_two --scenario 2"
data_script: "create_dataset.py"
# Distance related arguments
dynamic: False
distance_path: distances
distance_vars: "--variables cont"
# GLasso algorithm
gemini:
  - "mmd"
  - "wasserstein"
mode:
  - "ova"
  - "ovo"
lasso_vars: "--use_cuda --dims 5 --feature_threshold 2  --dropout 0.0 --epochs 200 --batch_size 200 -K 4 --lambda_start 1 --lambda_multiplier 1.05"
num_runs: 20
